# ID BOX:
# Name: Amal Ali
# Assignment #1
# Lab Section: X06L
# Lab Instructor’s Name: Dhara wagh
# Lecture Instructor’s Name: Ardy RD
# File purpose: To compile several C source codes with one command


# Variables/ Macros:
CC = gcc 
CFLAGS= -Wall -std=c99
PACKAGE_NAME = cmpt201_A1_AA.tar.gz
LDFLAGS = -lm

# Target 1:

#Clean: Cleans out all the executable files 
clean:
	 rm *.o 

#Packagae: Condenses all the specified files into a tarball
package:
	tar -czvf $(PACKAGE_NAME) 

